#!/bin/sh

target=""
while getopts "t:" flag; do
    case $flag in
        t) target=$OPTARG;;
        *) echo "Unkown $flag"
    esac
done

echo $target
F=$(base64 /dev/urandom | head -c5)
echo "Lorem ipsum CCIT{$F}."

sleep 10